// Path: src/pages/Packaging-inventory-list/data.ts

import type { PackagingItem } from "./types";

export const DUMMY_PACKAGING_DATA: PackagingItem[] = [
  {
    id: "PKG-CTN-001-L",
    qrCode: "PKG-CTN-001-L",
    itemNumber: "CTN-001",
    itemCategory: "Thùng Carton",
    materialName: "Thùng carton 5 lớp",
    color: "Nâu",
    size: "60x40x40 cm",
    quantity: 1200,
    unit: "Thùng",
    location: "Kệ P-01-A",
    requiredQuantity: 200,
    status: "In Stock",
    batchNumber: "CTN231001",
    dateReceived: "2023-10-01",
    supplier: "Bao bì Toàn Quốc",
    poNumber: "PO-PKG-081",
    reorderPoint: 300,
    lastModifiedDate: "2023-10-25",
    lastModifiedBy: "Khoa Nguyễn",
    description: "Thùng carton lớn để đóng gói áo khoác.",
  },
  {
    id: "PKG-POLY-002-M",
    qrCode: "PKG-POLY-002-M",
    itemNumber: "POLY-002",
    itemCategory: "Túi Poly",
    materialName: "Túi poly có khóa zip",
    color: "Trong suốt",
    size: "30x40 cm",
    quantity: 4500,
    unit: "Túi",
    location: "Kệ P-02-B",
    requiredQuantity: 1000,
    status: "In Stock",
    batchNumber: "POLY230925",
    dateReceived: "2023-09-25",
    supplier: "Nhựa Rạng Đông",
    poNumber: "PO-PKG-075",
    reorderPoint: 1000,
    lastModifiedDate: "2023-10-26",
    lastModifiedBy: "Linh Trần",
    description: "Túi poly để đóng gói áo thun, có lỗ thoát hơi.",
  },
  {
    id: "PKG-TAPE-001",
    qrCode: "PKG-TAPE-001",
    itemNumber: "TAPE-001",
    itemCategory: "Băng keo",
    materialName: "Băng keo trong",
    color: "Trong suốt",
    size: "4.8cm x 100m",
    quantity: 85,
    unit: "Cuộn",
    location: "Kệ P-05-C",
    requiredQuantity: 20,
    status: "Low Stock",
    batchNumber: "TAPE230901",
    dateReceived: "2023-09-01",
    supplier: "Băng keo Hùng Vương",
    poNumber: "PO-PKG-068",
    reorderPoint: 100,
    lastModifiedDate: "2023-10-24",
    lastModifiedBy: "Khoa Nguyễn",
    description: "Băng keo dán thùng carton, độ dính cao.",
  },
  {
    id: "PKG-LBL-003",
    qrCode: "PKG-LBL-003",
    itemNumber: "LBL-003",
    itemCategory: "Nhãn",
    materialName: "Nhãn vận chuyển",
    color: "Trắng",
    size: "10x15 cm",
    quantity: 0,
    unit: "Cái",
    location: "Kệ P-03-A",
    requiredQuantity: 2000,
    status: "Out of Stock",
    batchNumber: "LBL230815",
    dateReceived: "2023-08-15",
    supplier: "Giấy in An Lộc",
    poNumber: "PO-PKG-052",
    reorderPoint: 500,
    lastModifiedDate: "2023-10-15",
    lastModifiedBy: "Linh Trần",
    description: "Nhãn in thông tin vận chuyển, có keo dán sẵn.",
  },
  {
    id: "PKG-PAP-001",
    qrCode: "PKG-PAP-001",
    itemNumber: "PAP-001",
    itemCategory: "Giấy lót",
    materialName: "Giấy nến lót",
    color: "Trắng",
    size: "40x60 cm",
    quantity: 15000,
    unit: "Tờ",
    location: "Kệ P-04-D",
    requiredQuantity: 3000,
    status: "In Stock",
    batchNumber: "PAP231010",
    dateReceived: "2023-10-10",
    supplier: "Giấy Vĩnh Phú",
    poNumber: "PO-PKG-085",
    reorderPoint: 2000,
    lastModifiedDate: "2023-10-22",
    lastModifiedBy: "Khoa Nguyễn",
    description: "Giấy lót giữa các lớp áo để chống nhăn.",
  },
  {
    id: "PKG-CTN-002-S",
    qrCode: "PKG-CTN-002-S",
    itemNumber: "CTN-002",
    itemCategory: "Thùng Carton",
    materialName: "Thùng carton 3 lớp",
    color: "Nâu",
    size: "30x20x15 cm",
    quantity: 2500,
    unit: "Thùng",
    location: "Kệ P-01-B",
    requiredQuantity: 500,
    status: "In Stock",
    batchNumber: "CTN231005",
    dateReceived: "2023-10-05",
    supplier: "Bao bì Toàn Quốc",
    poNumber: "PO-PKG-083",
    reorderPoint: 500,
    lastModifiedDate: "2023-10-25",
    lastModifiedBy: "Linh Trần",
    description: "Thùng carton nhỏ cho phụ kiện hoặc đơn hàng nhỏ.",
  },
];