// Path: src/pages/accessory-inventory-list/data.ts

import type { AccessoryItem } from "./types";

export const DUMMY_ACCESSORY_DATA: AccessoryItem[] = [
  {
    id: "ACC-BTN-001-BLK",
    qrCode: "ACC-BTN-001-BLK",
    itemNumber: "BTN-001",
    itemCategory: "BTN",
    materialName: "Cúc nhựa 4 lỗ",
    color: "Đen",
    size: "15mm",
    quantity: 5000,
    unit: "Cái",
    location: "Kệ A-01-05",
    requiredQuantity: 500,
    status: "In Stock",
    batchNumber: "B20231001",
    dateReceived: "2023-10-01",
    supplier: "Phụ liệu Phong Phú",
    poNumber: "PO23-115",
    reorderPoint: 1000,
    lastModifiedDate: "2023-10-26",
    lastModifiedBy: "Nguyễn Văn An",
    description: "Cúc nhựa thông dụng cho áo sơ mi nam.",
  },
  {
    id: "ACC-ZIP-001-BRS",
    qrCode: "ACC-ZIP-001-BRS",
    itemNumber: "ZIP-001",
    itemCategory: "ZIP",
    materialName: "Khóa kéo kim loại",
    color: "Đồng",
    size: "50cm",
    quantity: 850,
    unit: "Cái",
    location: "Kệ B-03-01",
    requiredQuantity: 200,
    status: "In Stock",
    batchNumber: "Z20230915",
    dateReceived: "2023-09-15",
    supplier: "Dệt may Thành Công",
    poNumber: "PO23-098",
    reorderPoint: 200,
    lastModifiedDate: "2023-10-25",
    lastModifiedBy: "Trần Thị Bích",
    description: "Dùng cho áo khoác jean, loại răng 5.",
  },
  {
    id: "ACC-THR-001-WHT",
    qrCode: "ACC-THR-001-WHT",
    itemNumber: "THR-001",
    itemCategory: "THR",
    materialName: "Chỉ may polyester",
    color: "Trắng",
    size: "40/2",
    quantity: 150,
    unit: "Cuộn",
    location: "Kệ C-02-11",
    requiredQuantity: 30,
    status: "In Stock",
    batchNumber: "T20231010",
    dateReceived: "2023-10-10",
    supplier: "Sợi Việt Thắng",
    poNumber: "PO23-121",
    reorderPoint: 50,
    lastModifiedDate: "2023-10-26",
    lastModifiedBy: "Lê Minh Tuấn",
    description: "Chỉ may vắt sổ, độ bền cao.",
  },
  {
    id: "ACC-BTN-002-BRN",
    qrCode: "ACC-BTN-002-BRN",
    itemNumber: "BTN-002",
    itemCategory: "BTN",
    materialName: "Cúc gỗ 2 lỗ",
    color: "Nâu",
    size: "20mm",
    quantity: 90,
    unit: "Cái",
    location: "Kệ A-01-06",
    requiredQuantity: 200,
    status: "Low Stock",
    batchNumber: "B20230820",
    dateReceived: "2023-08-20",
    supplier: "Phụ liệu Sài Gòn",
    poNumber: "PO23-075",
    reorderPoint: 100,
    lastModifiedDate: "2023-10-24",
    lastModifiedBy: "Trần Thị Bích",
    description: "Cúc trang trí cho áo khoác len.",
  },
  {
    id: "ACC-LBL-001-MLT",
    qrCode: "ACC-LBL-001-MLT",
    itemNumber: "LBL-001",
    itemCategory: "LBL",
    materialName: "Nhãn dệt logo",
    color: "Nhiều màu",
    size: "2cm x 5cm",
    quantity: 0,
    unit: "Cái",
    location: "Kệ D-05-02",
    requiredQuantity: 1000,
    status: "Out of Stock",
    batchNumber: "L20230701",
    dateReceived: "2023-07-01",
    supplier: "Nhãn mác An Phát",
    poNumber: "PO23-050",
    reorderPoint: 500,
    lastModifiedDate: "2023-10-20",
    lastModifiedBy: "Nguyễn Văn An",
    description: "Nhãn dệt chính cho áo T-shirt.",
  },
  {
    id: "ACC-ELS-001-WHT",
    qrCode: "ACC-ELS-001-WHT",
    itemNumber: "ELS-001",
    itemCategory: "ELS",
    materialName: "Thun dệt kim",
    color: "Trắng",
    size: "2.5cm",
    quantity: 2500,
    unit: "Mét",
    location: "Kệ C-04-08",
    requiredQuantity: 800,
    status: "In Stock",
    batchNumber: "E20230928",
    dateReceived: "2023-09-28",
    supplier: "Phụ liệu Phong Phú",
    poNumber: "PO23-109",
    reorderPoint: 500,
    lastModifiedDate: "2023-10-26",
    lastModifiedBy: "Lê Minh Tuấn",
    description: "Thun luồn lưng quần thể thao.",
  },
  {
    id: "ACC-INT-001-WHT",
    qrCode: "ACC-INT-001-WHT",
    itemNumber: "INT-001",
    itemCategory: "INT",
    materialName: "Keo giấy dựng cổ",
    color: "Trắng",
    size: "90cm",
    quantity: 800,
    unit: "Mét",
    location: "Kệ B-01-03",
    requiredQuantity: 150,
    status: "In Stock",
    batchNumber: "I20230905",
    dateReceived: "2023-09-05",
    supplier: "Dệt may Thành Công",
    poNumber: "PO23-088",
    reorderPoint: 150,
    lastModifiedDate: "2023-10-22",
    lastModifiedBy: "Nguyễn Văn An",
    description: "Keo ủi dùng cho cổ và nẹp áo sơ mi.",
  },
  {
    id: "ACC-ZIP-002-RED",
    qrCode: "ACC-ZIP-002-RED",
    itemNumber: "ZIP-002",
    itemCategory: "ZIP",
    materialName: "Khóa kéo giọt nước",
    color: "Đỏ",
    size: "20cm",
    quantity: 320,
    unit: "Cái",
    location: "Kệ B-03-09",
    requiredQuantity: 100,
    status: "In Stock",
    batchNumber: "Z20231005",
    dateReceived: "2023-10-05",
    supplier: "Phụ liệu Sài Gòn",
    poNumber: "PO23-118",
    reorderPoint: 100,
    lastModifiedDate: "2023-10-25",
    lastModifiedBy: "Trần Thị Bích",
    description: "Khóa kéo giấu, dùng cho đầm nữ.",
  },
  {
    id: "ACC-THR-002-NVY",
    qrCode: "ACC-THR-002-NVY",
    itemNumber: "THR-002",
    itemCategory: "THR",
    materialName: "Chỉ may cotton",
    color: "Xanh Navy",
    size: "50/3",
    quantity: 45,
    unit: "Cuộn",
    location: "Kệ C-02-12",
    requiredQuantity: 60,
    status: "Low Stock",
    batchNumber: "T20230815",
    dateReceived: "2023-08-15",
    supplier: "Sợi Việt Thắng",
    poNumber: "PO23-070",
    reorderPoint: 50,
    lastModifiedDate: "2023-10-26",
    lastModifiedBy: "Lê Minh Tuấn",
    description: "Chỉ cotton chần cho quần kaki.",
  },
  {
    id: "ACC-LBL-002-WHT",
    qrCode: "ACC-LBL-002-WHT",
    itemNumber: "LBL-002",
    itemCategory: "LBL",
    materialName: "Nhãn satin in HDSD",
    color: "Trắng",
    size: "3cm x 6cm",
    quantity: 4500,
    unit: "Cái",
    location: "Kệ D-05-03",
    requiredQuantity: 0,
    status: "In Stock",
    batchNumber: "L20231012",
    dateReceived: "2023-10-12",
    supplier: "Nhãn mác An Phát",
    poNumber: "PO23-124",
    reorderPoint: 1000,
    lastModifiedDate: "2023-10-23",
    lastModifiedBy: "Nguyễn Văn An",
    description: "Nhãn sườn in hướng dẫn sử dụng.",
  },
];