// Path: src/pages/sewing-trims-kanban/data.ts
// Changes: The `job` property now contains specific job codes instead of generic names.

import type { KanbanBoard, Assignee } from "./types";

const users: Record<string, Assignee> = {
  'lan.nguyen': { id: 'user-lan', name: 'Nguyễn Thị Lan' },
  'hung.tran': { id: 'user-hung', name: 'Trần Văn Hùng' },
  'hoa.le': { id: 'user-hoa', name: 'Lê Thị Hoa' },
  'bach.pham': { id: 'user-bach', name: 'Phạm Văn Bách' },
  'tu.hoang': { id: 'user-tu', name: 'Hoàng Minh Tú' },
}

export const mockSewingBoard: KanbanBoard[] = [
  {
    id: "sewing-line-trims-request",
    name: "Sewing Line - Trims Request",
    tasks: [
      {
        id: 'KB-001',
        requestName: 'Yêu cầu vải chính JKT-0821',
        dateCreated: '2023-11-20 08:00',
        dateRequired: '2023-11-20',
        factoryLine: 'Chuyền 1',
        style: 'JKT-0821',
        job: 'CUT-0821-01', // Changed
        color: 'Black',
        size: 'M',
        poNumber: 'PO-23-US-5512',
        requiredQuantity: 500,
        issuedQuantity: 0,
        status: 'New',
        priority: 'High',
        bomId: 'BOM-JKT-0821-V2',
        createdBy: users['lan.nguyen'],
        remarks: 'Cần gấp để kịp tiến độ cắt.',
      },
      {
        id: 'KB-002',
        requestName: 'Cấp chỉ may PNT-5503',
        dateCreated: '2023-11-19 14:30',
        dateRequired: '2023-11-20',
        factoryLine: 'Chuyền 3',
        style: 'PNT-5503',
        job: 'SEW-5503-05', // Changed
        color: 'Navy',
        size: 'L',
        poNumber: 'PO-23-EU-8904',
        requiredQuantity: 1200,
        issuedQuantity: 1200,
        status: 'Completed',
        priority: 'Medium',
        bomId: 'BOM-PNT-5503-V1',
        createdBy: users['hung.tran'],
        remarks: 'Đã nhận đủ hàng.',
      },
      {
        id: 'KB-003',
        requestName: 'Yêu cầu cúc áo SHRT-112A',
        dateCreated: '2023-11-20 09:15',
        dateRequired: '2023-11-21',
        factoryLine: 'Chuyền 5',
        style: 'SHRT-112A',
        job: 'FIN-112A-02', // Changed
        color: 'White',
        size: 'S',
        poNumber: 'PO-23-JP-7765',
        requiredQuantity: 800,
        issuedQuantity: 500,
        status: 'Partially Issued',
        priority: 'Medium',
        bomId: 'BOM-SHRT-112A-V1',
        createdBy: users['hoa.le'],
        remarks: 'Kho báo sẽ cấp phần còn lại vào chiều nay.',
      },
      {
        id: 'KB-004',
        requestName: 'Lấy vải lót cho JKT-0821',
        dateCreated: '2023-11-20 10:00',
        dateRequired: '2023-11-20',
        factoryLine: 'Chuyền 1',
        style: 'JKT-0821',
        job: 'SEW-0821-03', // Changed
        color: 'Black',
        size: 'M',
        poNumber: 'PO-23-US-5512',
        requiredQuantity: 500,
        issuedQuantity: 0,
        status: 'Ready for Pickup',
        priority: 'Medium',
        bomId: 'BOM-JKT-0821-V2',
        createdBy: users['lan.nguyen'],
        remarks: 'Kho đã soạn xong, chờ tổ trưởng nhận.',
      },
      {
        id: 'KB-005',
        requestName: 'Yêu cầu dây kéo cho PNT-5503',
        dateCreated: '2023-11-20 11:25',
        dateRequired: '2023-11-21',
        factoryLine: 'Chuyền 3',
        style: 'PNT-5503',
        job: 'SEW-5503-08', // Changed
        color: 'Navy',
        size: 'L',
        poNumber: 'PO-23-EU-8904',
        requiredQuantity: 1200,
        issuedQuantity: 0,
        status: 'Confirmed',
        priority: 'Medium',
        bomId: 'BOM-PNT-5503-V1',
        createdBy: users['hung.tran'],
      },
       {
        id: 'KB-007',
        requestName: 'Yêu cầu nhãn mác cho SHRT-112A',
        dateCreated: '2023-11-21 13:00',
        dateRequired: '2023-11-22',
        factoryLine: 'Chuyền 5',
        style: 'SHRT-112A',
        job: 'FIN-112A-09', // Changed
        color: 'White',
        size: 'S, M, L',
        poNumber: 'PO-23-JP-7765',
        requiredQuantity: 2400,
        issuedQuantity: 0,
        status: 'Picking',
        priority: 'Low',
        bomId: 'BOM-SHRT-112A-V1',
        createdBy: users['hoa.le'],
        remarks: 'Kho đang tìm hàng.',
      },
       {
        id: 'KB-009',
        requestName: 'Hủy yêu cầu vải JKT-0821',
        dateCreated: '2023-11-22 10:45',
        dateRequired: '2023-11-22',
        factoryLine: 'Chuyền 1',
        style: 'JKT-0821',
        job: 'CUT-0821-02', // Changed
        color: 'Beige',
        size: 'S',
        poNumber: 'PO-23-US-5512',
        requiredQuantity: 250,
        issuedQuantity: 0,
        status: 'Cancelled',
        priority: 'Low',
        bomId: 'BOM-JKT-0821-V2',
        createdBy: users['lan.nguyen'],
        remarks: 'Đổi mã màu, sẽ tạo yêu cầu mới.',
      },
       {
        id: 'KB-010',
        requestName: 'Yêu cầu mex cổ cho SHRT-112A',
        dateCreated: '2023-11-23 08:10',
        dateRequired: '2023-11-24',
        factoryLine: 'Chuyền 5',
        style: 'SHRT-112A',
        job: 'CUT-112A-04', // Changed
        color: 'White',
        size: 'All sizes',
        poNumber: 'PO-23-JP-7765',
        requiredQuantity: 1500,
        issuedQuantity: 0,
        status: 'New',
        priority: 'Medium',
        bomId: 'BOM-SHRT-112A-V1',
        createdBy: users['hoa.le'],
      },
    ],
    columns: [
      { id: 'col-new', title: 'New', taskIds: ['KB-001', 'KB-010'] },
      { id: 'col-confirmed', title: 'Confirmed', taskIds: ['KB-005'] },
      { id: 'col-picking', title: 'Picking', taskIds: ['KB-007'] },
      { id: 'col-ready', title: 'Ready for Pickup', taskIds: ['KB-004'] },
      { id: 'col-partial', title: 'Partially Issued', taskIds: ['KB-003'] },
      { id: 'col-completed', title: 'Completed', taskIds: ['KB-002'] },
      { id: 'col-cancelled', title: 'Cancelled', taskIds: ['KB-009'] },
    ],
  },
];